frontend/src/components/CaseSelector.js
* Add dummy option to the start of options list in CaseSelector.js, to enable the first real option to be selected.
* Closes #22
=> add dummy option to the start of list for CaseSelector

frontend/src/components/CaseContainer.js
Makes the viewbox full width and centres the chart within it when first loaded. Closes https://github.com/alan-turing-institute/AssurancePlatform/issues/24
=> Centre chart view on load

frontend/src/components/CaseContainer.css, frontend/src/components/CaseContainer.js
Add a tooltip containing the "short_description" of an item.
Styling (including possibly non-desirable blue background) is in new file `CaseContainer.css`.
Addresses #50
=> Tooltip short description

frontend/src/components/CaseContainer.js, frontend/src/components/CaseSelector.js, frontend/src/components/Navigation.js, frontend/src/components/Routes.js
* Remove the sidebar in CaseContainer, leave only the Add Goal button and move it up to the level of the heading.
* Separate the CaseContainer heading from the content
* Add a dropdown menu for selecting or creating a case in the navbar
* To facilitate easy implementation of the above, change the route `/cases/id` to be `/case/id`.
closes https://github.com/alan-turing-institute/AssurancePlatform/issues/52
closes https://github.com/alan-turing-institute/AssurancePlatform/issues/46
=> Restructure navigation

eap_backend/eap_api/views.py, frontend/src/caseTemplates/empty.json, frontend/src/caseTemplates/minimal.json, frontend/src/components/CaseContainer.js, frontend/src/components/CaseCreator.js, frontend/src/components/ItemCreator.js, frontend/src/components/ItemViewer.js, frontend/src/components/TemplateSelector.js
Adds to the `case_list` POST end point the capacity to receive cases with content, and uses that to implement templates. Templates are all JSON files in `frontend/src/caseTemplates`.
Also includes a few unrelated style changes, that remove unused code and such. These were things that a linter was complaining about.
Partially addresses https://github.com/alan-turing-institute/AssurancePlatform/issues/44, though no thumbnails yet, just a dropdown menu on the case creation page.
=> Add templates

frontend/src/components/CaseContainer.js, frontend/src/components/EditableText.js, frontend/src/components/tests/CaseContainer.test.js
Front end elements for editing and deleting cases.
The text boxes for name and description are editable. Edits are submitted to the backend whenever the text box loses focus (e.g. user clicks somewhere else or navigates away) or there's a submit event, such as hitting enter.
Draft while I figure out the test failure.
Closes https://github.com/alan-turing-institute/AssurancePlatform/issues/54
=> Make case name and description editable, and cases deletable

frontend/src/components/App.css, frontend/src/components/CaseContainer.js, frontend/src/components/Routes.js
Remove copyright bar from grid display in CaseContainer, and instead have as a div with class "App-footer" (and include styling via `App.css`) in `Routes.js`.   This will ensure it is always at the bottom of the screen.
=> Add footer to Routes, and remove from CaseContainer

frontend/src/components/CaseContainer.js, frontend/src/components/Home.js
* Fix the height of the image on the homepage so it doesn't get too big when browser is full screen.
* First attempt at rearranging buttons on the CaseContainer component.
=> fix some low-hanging layout fruit

eap_backend/eap_api/models.py, eap_backend/eap_api/view_utils.py, eap_backend/eap_api/views.py, eap_backend/tests/test_views.py
When moving Property Claims under other property claims, we trigger the property claim logic.
=> Trigger identifier update when moving property claims.

CONTRIBUTING.md, eap_backend/tests/test_views.py
As reported in https://github.com/alan-turing-institute/AssurancePlatform/issues/489 , the identifier assignment became inconsistent. In this PR, we have an automated test that checks identifiers follow insertion order.
=> Testing consistent identifiers when creating multiple strategies

eap_backend/eap_api/urls.py, eap_backend/eap_api/views.py, next_frontend/.env.local, next_frontend/components/cases/NotesEditForm.tsx, next_frontend/components/cases/NotesFeed.tsx, next_frontend/components/cases/NotesForm.tsx
- API now has a new endpoint for fetching a single comment as well as update and delete
- Reworked the `/comments/{assurance_case_id}/` endpoint to make this work with the above
- Ability for a user to toggle whether they would like to edit the comment or not
- Ability for a user to remove the comment
=> Note edit and delete

next_frontend/components/common/NodeEdit.tsx, next_frontend/components/modals/alertModal.tsx
Modifying the `Alert` component to handle custom description and button text based on where the component is placed. This change is primarily for the following:
- When editing and closing the panel without saving changes
- When deleting an element - letting the user know this will also remove child elements
=> Alert pop up changes

eap_backend/eap_api/serializers.py, eap_backend/eap_api/views.py, eap_backend/tests/constants_tests.py, eap_backend/tests/test_views.py
Before this PR, case item creation with POST only returned `id` and `name`. Now, we return a complete serialised case item. We also addressed the missing `type` value for strategies when retrieving cases.
=> Return serialised case items when creating them with POST

eap_backend/eap_api/view_utils.py, eap_backend/eap_api/views.py, eap_backend/tests/test_views.py
The algorithm now has the following considerations, regarding top-level property claims (i.e. children of the goal of a strategy):
- Property claim under goals, always have a lower identifier than property claims under strategies: In the current version of the TEA platform, property claims are always placed to the left of strategies. When issue https://github.com/alan-turing-institute/AssurancePlatform/issues/539 is delivered, we'll need to change this logic.
- Property claims from different strategies have their identifiers reflecting their parents (i.e. property claims under `S1`, will have identifiers inferior to the claims under `S2`.
- The rest of the logic remains the same, where we sort by order of insertion.
=> The "Update Identifier" logic is now aware of claim parents

eap_backend/eap_api/view_utils.py, eap_backend/tests/test_views.py
Evidence was not expanding when serialising a case sandbox. This PR fixes that.
=> Expanding evidence for property claims in sandbox

next_frontend/components/Header.tsx, next_frontend/data/store.ts, next_frontend/lib/case-helper.ts
For implemented this feature:
1. In `Header.tsx`, I added the `unhideParents` function, which is called as part of the `focusNode` method invoked when selecting a case element from the case results.
2. In `unhideParents`, we call `toggleHiddenForParent` (from `case-helper.ts`) for obtaining a new case representation, where the relevant nodes have `node.hidden == false`. This new case representation is placed in the store via `setAssuranceCase`.
3. The `toggleHiddenForParent` method uses [deep-first search](https://en.wikipedia.org/wiki/Depth-first_search) (implement in `searchWithDeepFirst`) to find the case elements to unhide.
4. @RichGriff made some updates to `store.ts`, to fix some issues when zooming to the selected case element.
=> Search for elements within collapsed  case elements

eap_backend/eap_api/model_utils.py, eap_backend/eap_api/serializers.py, eap_backend/eap_api/view_utils.py, eap_backend/eap_api/views.py, eap_backend/tests/test_views.py
After a POST request to create a case element (Goal, Context, Strategy, Evidence) the JSON document returned will include a name that's unique within then assurance case.
=> Return unique name after case element creation

next_frontend/components/common/NewLinkForm.tsx, next_frontend/lib/case-helper.ts
A bit of a clean up when creating new linked elements. 
Also ensured that we are using the result to update the assurance case in state.
=> Ensure result is rendered for the element

eap_backend/eap_api/github.py, eap_backend/eap_api/urls.py, eap_backend/eap_api/view_utils.py, eap_backend/eap_api/views.py, eap_backend/eap_backend/settings.py, eap_backend/requirements.txt, eap_backend/tests/test_views.py
When a valid access token is sent from the frontend, we create/retrieve the corresponding TEA user from the database, and generate a new authentication token
=> Exchanging a GitHub access token for a Authentication Token 

eap_backend/eap_api/serializers.py, eap_backend/eap_api/urls.py, eap_backend/eap_api/views.py, eap_backend/tests/test_views.py
To consume the endpoint, do a `PUT` request to endpoint `users/<user-id>/change-password` with body `{"password": <current-password>, "new_password": <new-password>}` , to set the password of user with ID `<user-id>`to `<new-password>`. The user needs to provide the old password (`<current-password>`) and the authorization token.
=> New endoint for password change

eap_backend/eap_api/view_utils.py, eap_backend/eap_api/views.py, eap_backend/tests/test_permissions.py, eap_backend/tests/test_views.py, next_frontend/components/cases/NoCasesFound.tsx
The `cases` endpoint has three additional query parameters: `owner`, `view`, and `edit`, that can be used to filter the cases per user:
1. `GET cases/` still behaves as usual, returning **all** the cases a user has permissions. It is equivalent to `GET cases?owner=true&view=true&edit=true` 
2. `GET cases?owner=false&view=true&edit=true` can be used to retrieve the cases a user has view/edit permissions, but it's not the owner. This can be used to populate the "Shared with me" page.
=> Additional options for case retrieval
