alan-turing-institute/AssurancePlatform

- frontend/src/components/ItemCreator.js
- frontend/src/components/ItemEditor.js
Fix a couple of issues where occasionally the page would reload before the insertion/deletion of an item had propagated to the backend. Also silence one inconsequential React error that was filling up the logs.
> Miscellaneous small bug fixes

- frontend/src/components/CaseCreator.js
- frontend/src/components/TemplateSelector.js
* Send the description to the backend
* Use the Empty template by default
Closes https://github.com/alan-turing-institute/AssurancePlatform/issues/72
Closes https://github.com/alan-turing-institute/AssurancePlatform/issues/67
> Fix two bugs in CaseCreator

- frontend/src/components/ItemEditor.js
Closes https://github.com/alan-turing-institute/AssurancePlatform/issues/71
> Fix race condition when editing items

- HOWTO_deploy_to_Azure.md
- eap_backend/eap_api/models.py
- frontend/src/components/CaseContainer.js
- frontend/src/components/ItemEditor.js
- frontend/src/components/ParentSelector.js
- frontend/src/components/utils.js
- frontend/src/config.json
Had to change to the new way of getting the base URL in the multiple parents code.
> Fix multiple parents

- frontend/src/components/ItemCreator.js
Add debug statement to see if state change in ItemCreator is working
> debug statement for multiple submit

- frontend/src/components/Signup.js
Use the response from the backend to give the user feedback on why their sign-up didn't work.
> display error messages for sign-up errors

- frontend/src/components/ItemEditor.js
- frontend/src/components/tests/ItemEditor.test.js
Make the fields in ItemEditor keep their old value when you start editing.
> Make existing values easier to edit in ItemEditor

- frontend/src/components/Home.js
Make the image on Home.js scale nicely depending on window size
> Make the image on Home.js scale nicely

- frontend/src/components/ItemEditor.js
- frontend/src/components/Login.js
- frontend/src/components/Signup.js
- frontend/src/components/tests/ItemEditor.test.js
Make signup use grommet all over, and convert the last remaining non-grommet elements of login too.
Built, for no good reason, on top of https://github.com/alan-turing-institute/AssurancePlatform/pull/127, so may make sense to merge that first.
> Prettier signup

- frontend/src/components/ItemEditor.js
Fixes https://github.com/alan-turing-institute/AssurancePlatform/issues/48
> Fix a couple of issues with race conditions

- site/docs/about.md
just some minor typos I noticed when reading through the website
> fix typos on website about page

- eap_backend/eap_api/github.py
- eap_backend/eap_api/views.py
- frontend/src/components/Github.js
- frontend/src/components/GithubFileManager.js
- frontend/src/components/GithubRepositories.js
- frontend/src/components/Routes.js
Doing a partial merge to improve live version of things
> Improved GitHub

- frontend/src/components/CaseContainer.js
> Fix graphical bug

- frontend/src/components/Mermaid.js
potential fix for https://github.com/alan-turing-institute/AssurancePlatform/issues/306
> Fix Mermaid chart rendering and update logic

- frontend/src/components/CaseCreator.js
> Refactor CaseCreator component

- frontend/src/config.json
> Adding and moving parents is broken

- frontend/src/components/CaseContainer.js
- frontend/src/components/ItemCreator.js
- frontend/src/components/ItemEditor.js
- frontend/src/components/tests/ItemCreator.test.js
- frontend/src/components/tests/ItemEditor.test.js
- frontend/src/components/utils.js
PR for #296 
I've replaced the name field rather than add a new field to the database, as I believe the plan was to deprecate that field as part of the UI overhaul.
I think there's some question over whether this is correct for existing graphs in the database.
> Add element identifiers

- site/docs/index.md
Adding funding statement to homepage for end of year report.
> add funding statement

- frontend/src/components/CaseMediaPreview.jsx
- frontend/src/components/ManageCases.jsx
- frontend/src/components/Mermaid.js
- frontend/src/config.json
Render mermaid charts on the case items on the manage cases screen to act as a preview image before selecting a case to view/edit.
Closes #331, and there are notes in the issue explaining how this was implemented.
> case preview SVG

- frontend/src/components/CaseImporterFlow.jsx
> "Url" should be "URL"

- frontend/src/Theming.jsx
- frontend/src/components/utils.js
- frontend/src/config.json
> Remove hard-coded theme elements

- eap_backend/eap_api/view_utils.py
> Checking for int or str and then fetching case

- examples/README.md
- examples/report-it.json
- examples/synthetic-data-quality.json
@aranas, here are the two demo cases/patterns that you can use. I believe you will need to provide the URL for the raw JSON when importing into the platform.
> add example cases and create new directory

- site/docs/platform-details/backend/api/assurance-cases.md
- site/docs/platform-details/backend/api/authentication.md
- site/docs/platform-details/backend/api/comment.md
- site/docs/platform-details/backend/api/github.md
- site/docs/platform-details/backend/api/group.md
- site/docs/platform-details/backend/api/index.md
- site/docs/platform-details/backend/api/user.md
- site/docs/platform-details/backend/installation.md
- site/docs/platform-details/docker-quickstart.md
- site/docs/platform-details/frontend/installation.md
- site/docs/platform-details/reset-database/azure.md
- site/docs/platform-details/reset-database/local.md
> Remove `$` from code blocks in documentation

- README.md
Pedantic grammar updates, but important for first-impressions!
> chore: README.md Docs

- next_frontend/components/cases/ActionButtons.tsx
- next_frontend/components/cases/CaseCard.tsx
- next_frontend/components/cases/ToggleButton.tsx
- next_frontend/components/common/EditForm.tsx
- next_frontend/components/common/NodeEdit.tsx
- next_frontend/components/modals/alertModal.tsx
- next_frontend/components/ui/navigation-menu.tsx
- next_frontend/lib/case-helper.ts
- next_frontend/lib/convert-case.ts
These include various bug fixes identified from the workshops. 
Not all bugs are included, some need further investigation and approval, please see open issues for these.
> Various bug fixes

- next_frontend/components/cases/NotesFeed.tsx
Toggle bug fix that only sets the current note to edit mode
> Toggle edit fix

- next_frontend/components/common/NodeEdit.tsx
The ability to move Property Claims to Goals
> 482 Claims under Goals

- next_frontend/lib/case-helper.ts
Incorrectly setting hidden value on evidence. Correction was to look at at parent hidden if there are no siblings.
> Evidence Bug Fix

- next_frontend/components/cases/ActionButtons.tsx
- next_frontend/components/common/CreateForm.tsx
- next_frontend/components/common/NewLinkForm.tsx
- next_frontend/components/common/NodeCreate.tsx
- next_frontend/components/common/NodeEdit.tsx
- next_frontend/components/ui/create-sheet.tsx
- Discard alert copy correction
- Discard alert added to:
-- New goal element
-- New Link Element
> alert on new elements

- eap_backend/eap_api/views.py
Receiving the user email from the frontend
> Receiving user email from the frontend

- next_frontend/components/cases/ActionButtons.tsx
- next_frontend/components/cases/CaseCard.tsx
- next_frontend/components/cases/CaseDetails.tsx
- next_frontend/components/cases/CaseEditForm.tsx
- next_frontend/components/cases/Flow.tsx
- next_frontend/components/common/EditForm.tsx
- next_frontend/components/modals/PermissionsModal.tsx
- next_frontend/components/modals/ShareModal.tsx
Showing and hiding elements/actions based on the users permission level - for Reviewer and Edit
> 569 reviewer permissions

- next_frontend/app/(main)/dashboard/page.tsx
- next_frontend/components/cases/CaseList.tsx
- next_frontend/components/cases/CommentsFeed.tsx
- next_frontend/components/cases/NotesEditForm.tsx
- next_frontend/components/cases/NotesFeed.tsx
- next_frontend/components/cases/NotesForm.tsx
- next_frontend/components/common/NodeEdit.tsx
- next_frontend/data/store.ts
This has now been fixed and also handled that users can only edit/delete their own comments
> 627 reviewer comments

- README.md
Attempting fix of all-contributors
> Fix all-contributors

- eap_backend/eap_api/migrations/0039_casestudy_type.py
- eap_backend/eap_api/views.py
- next_frontend/app/(landing)/discover/[id]/page.tsx
- next_frontend/app/(main)/dashboard/case-studies/_components/RelatedAssuranceCaseList.tsx
Check render of multiple authors and fix if needed
Remove Category badge as this is not needed
> Render authors, remove category

- next_frontend/app/(landing)/cookie-policy/page.tsx
- next_frontend/app/(landing)/layout.tsx
- next_frontend/components/CookieConsent.tsx
- Cookie policy page added
- Consent popup added
> Policy Page added and Consent popup added

- next_frontend/components/auth/RegisterForm.tsx
This bug fix addresses an issue with the submission form and enhances the UX to notify the user that there submission is in progress.
> enhance UX and fix bug related to registration form
